<?php
/*
 * 1. https://tilda.cc/ru/privacy-generator/ - Конструктор политики обработки персональных данных
 * 2. https://docs.google.com/document/d/1S3BWelBgWtYTwXefoTxUH8b6yCFkMEp6xLBDIXdsAu4/edit?tab=t.0#heading=h.y0q9mj9bjhz - чек лист
 * 3. https://pd.rkn.gov.ru/operators-registry/notification/form/ - РКН
 */
/**
 * Implements hook_menu().
 */
function r_cookies_modal_menu() {
  $items = [];

  $items['admin/config/cookies-modal'] = [
    'title' => 'Настройка Cookies Modal - 152 ФЗ',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['r_cookies_modal_form'],
    'access arguments' => ['administer r_cookies_modal'],
  ];
  return $items;
}

function r_cookies_modal_permission() {
  return [
    'administer r_cookies_modal' => [
      'title' => 'Доступ к r_cookies_modal',
    ],
  ];
}

function r_cookies_modal_form($form, &$form_state) {
  $form['markup'] = [
    '#markup' => 'Конструктор политики обработки персональных данных: <a href="https://tilda.cc/ru/privacy-generator/" target="_blank">https://tilda.cc/ru/privacy-generator/</a>',
  ];
  /**
   * Политика обработки персональных данных
   **/
  $form['r_cookies_personal_data_processing_policy'] = [
    '#type' => 'textfield',
    '#title' => 'node/$nid - с политикой обработки персональных данных',
    '#default_value' => variable_get('r_cookies_personal_data_processing_policy', '<front>'),
    '#description' => l('Текущая ссылка на политику обработки персональных данных', variable_get('r_cookies_personal_data_processing_policy', '<front>')) . ',<br/>
<b>Пример ссылки:</b> node/1',
  ];
  /**
   * Согласие на обработку персональных данных
   **/
  $form['r_cookies_personal_data_processing_policy_consent'] = [
    '#type' => 'textfield',
    '#title' => 'node/$nid - Согласие на обработку персональных данных',
    '#default_value' => variable_get('r_cookies_personal_data_processing_policy', '<front>'),
    '#description' => l('Текущая ссылка на Согласие обработки персональных данных', variable_get('r_cookies_personal_data_processing_policy_consent', '<front>')) . ',<br/>
<b>Пример ссылки:</b> node/1',
  ];
  /**
   * Политика использования Cookies
   */
  $form['r_cookies_we_use_cookies'] = [
    '#type' => 'textfield',
    '#title' => 'node/$nid - с Политикой использования cookies',
    '#default_value' => variable_get('r_cookies_we_use_cookies', '<front>'),
    '#description' => l('Политика использования cookies', variable_get('r_cookies_we_use_cookies', '<front>')) . ',<br/>
<b>Пример ссылки:</b> node/1',
  ];
  /**
   * Согласие на получение рекламной и информационной рассылки
   */
  $form['r_cookies_advertising_newsletter'] = [
    '#type' => 'textfield',
    '#title' => 'node/$nid - Согласие на получение рекламной и информационной рассылки',
    '#default_value' => variable_get('r_cookies_advertising_newsletter', '<front>'),
    '#description' => l('Согласие на получение рекламной и информационной рассылки', variable_get('r_cookies_modal_cookies', '<front>')) . ',<br/>
<b>Пример ссылки:</b> node/1',
  ];


  return system_settings_form($form);
}


/**
 * Implements hook_block_info().
 */
function r_cookies_modal_block_info() {
  $blocks['r_cookies_modal_block'] = [
    'info' => t('Cookies modal block'), // Название блока в `admin/structure/block`
  ];
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function r_cookies_modal_block_view($delta = '') {
  $block = [];

  if ($delta == 'r_cookies_modal_block') {
    drupal_add_css(drupal_get_path('module', 'r_cookies_modal') . '/css/r_cookies_modal.less');
    drupal_add_js(drupal_get_path('module', 'r_cookies_modal') . '/js/r_cookies_modal.js');

    $block['subject'] = ''; // Заголовок блока (можно оставить пустым)
    $block['content'] = [
//      '#markup' => '<noindex>
//<div id="cookie_note">
//    <p>Мы используем cookie-файлы для улучшения работы сайта. Продолжая использовать сайт, вы соглашаетесь с ' .
//        l('политикой  использования cookies', variable_get('r_cookies_we_use_cookies', '<front>'), ['html' => true, 'attributes' => ['target' => '_blank']])
//        . ' и ' . l('защитой данных', variable_get('r_cookies_personal_data_processing_policy', '<front>'), ['html' => true, 'attributes' => ['target' => '_blank']]) . '.</p>
//    <span class="cookie_accept">Принять</span>
//    <span class="cookie_deny">Отклонить</span>
//</div>
//</noindex>',
      '#markup' => '<noindex>
<div id="cookie_note">
    <p>Мы используем файлы Cookies и метрические системы для сбора и анализа информации о производительности и использовании сайта, а также для улучшения и индивидуальной настройки предоставления информации. Нажимая кнопку «Принять» или продолжая пользоваться сайтом, вы соглашаетесь на размещение файлов Cookies и обработку данных метрических систем в соответствии с <a href="' . url(variable_get('r_cookies_personal_data_processing_policy', '<front>')) . '" target="_blank">Политикой</a>.</p>
    <span class="cookie_accept">Принять</span>
    <span class="cookie_deny">Отклонить</span>
</div>
</noindex>',
    ];
  }

  return $block;
}

/**
 * 1. `agreement` = «Я принимаю условия Политики в отношении обработки персональных данных» (слово «Политики» должно быть кликабельно, при переходе по кликабельной ссылке должен открываться текст Политики)
 * 2. `give_my_consent` = «Я даю Согласие на обработку моих персональных данных в соответствии с Политикой» (слова «Политика» и «Согласие» должны быть кликабельны, при переходе по кликабельным ссылкам должен открываться текст Согласия и текст Политики)
 * 3. `advertising_newsletter` = «Я даю Согласие на получение рекламной и информационной рассылки» (слово «Согласие» должно быть кликабельно, при переходе по кликабельной ссылке должен открываться текст Согласия)
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 * @return void
 */

function r_cookies_modal_form_alter(&$form, &$form_state, $form_id) {
  $webforms = [
    'webform_client_form_23',
    'webform_client_form_26',
  ];
  if (in_array($form_id, $webforms)) {
    if (isset($form['submitted']['agreement'])) {
//      dsm($form, '$form');
//      $form['submitted']['agreement']['#options']['agree'] = 'Даю согласие на обработку персональных данных в соответствии с ' . l( 'условиями', 'node/308', [ 'attributes' => [ 'target' => '_blank' ] ] );
//      $form['submitted']['agreement']['#options']['agree'] = 'Я <strong>согласен(-на)</strong> на обработку моих персональных данных в соответствии с <a href="' . url('node/309') . '" target="_blank">Положением</a> о защите <a href="' . url('node/308') . '" target="_blank">персональных данных</a>';
      $form['submitted']['agreement']['#options']['agree'] = 'Я принимаю условия <a class="r-cookies__link" href="' . url(variable_get('r_cookies_personal_data_processing_policy', '<front>')) . '" target="_blank">Политики</a> в отношении обработки персональных данных';
      $form['submitted']['give_my_consent']['#options']['agree'] = 'Я даю <a class="r-cookies__link" href="' . url(variable_get('r_cookies_personal_data_processing_policy_consent', '<front>')) . '" target="_blank">Согласие</a> на обработку моих персональных данных в соответствии с <a class="r-cookies__link" href="' . url(variable_get('r_cookies_personal_data_processing_policy', '<front>')) . '" target="_blank">Политикой</a>';
      $form['submitted']['advertising_newsletter']['#options']['agree'] = 'Я даю <a class="r-cookies__link" href="' . url(variable_get('r_cookies_advertising_newsletter', '<front>')) . '" target="_blank">Согласие</a> на получение рекламной и информационной рассылки';
    }
  }
}
